name: 'Matrix Sequential Lock'
description: 'Locking mechanism for GitHub Actions matrix workflows - controls execution order of matrix jobs'

branding:
  icon: 'lock'
  color: 'blue'

inputs:
  step:
    description: 'Action to perform: init (initialize lock), wait (wait for turn), or continue (release lock)'
    required: true
  order:
    description: 'Comma-separated list of job IDs in execution order (required for init step)'
    required: false
  id:
    description: 'Unique identifier for this job (required for wait and continue steps)'
    required: false
  retry-count:
    description: 'Maximum number of retry attempts to acquire the lock'
    default: '6'
    required: false
  retry-delay:
    description: 'Delay in seconds between retry attempts'
    default: '10'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
